// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/31/2025, 1:23:38 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/akarmain/Zed/vanilla_code/training/nuxt_tailwind/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/akarmain/Zed/vanilla_code/training/nuxt_tailwind/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/akarmain/Zed/vanilla_code/training/nuxt_tailwind/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/akarmain/Zed/vanilla_code/training/nuxt_tailwind/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/akarmain/Zed/vanilla_code/training/nuxt_tailwind/app/plugins/**/*.{js,ts,mjs}","/Users/akarmain/Zed/vanilla_code/training/nuxt_tailwind/app/composables/**/*.{js,ts,mjs}","/Users/akarmain/Zed/vanilla_code/training/nuxt_tailwind/app/utils/**/*.{js,ts,mjs}","/Users/akarmain/Zed/vanilla_code/training/nuxt_tailwind/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/akarmain/Zed/vanilla_code/training/nuxt_tailwind/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/akarmain/Zed/vanilla_code/training/nuxt_tailwind/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;